// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOjUyBMt3FTP-JcYf1ZhvWC_bBQzwRGM',
    appId: '1:490591202306:web:11195f6a9b17cac9f3cb1b',
    messagingSenderId: '490591202306',
    projectId: 'eventhub-mobileapp',
    authDomain: 'eventhub-mobileapp.firebaseapp.com',
    storageBucket: 'eventhub-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmK7aVIdxDsaL9hwI_KW5hv1R6GZcO4XE',
    appId: '1:490591202306:ios:a427b7ba75470c26f3cb1b',
    messagingSenderId: '490591202306',
    projectId: 'eventhub-mobileapp',
    storageBucket: 'eventhub-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmK7aVIdxDsaL9hwI_KW5hv1R6GZcO4XE',
    appId: '1:490591202306:ios:a427b7ba75470c26f3cb1b',
    messagingSenderId: '490591202306',
    projectId: 'eventhub-mobileapp',
    storageBucket: 'eventhub-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoOjUyBMt3FTP-JcYf1ZhvWC_bBQzwRGM',
    appId: '1:490591202306:web:7462ed004fda2da2f3cb1b',
    messagingSenderId: '490591202306',
    projectId: 'eventhub-mobileapp',
    authDomain: 'eventhub-mobileapp.firebaseapp.com',
    storageBucket: 'eventhub-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOjUyBMt3FTP-JcYf1ZhvWC_bBQzwRGM',
    appId: '1:490591202306:android:b2ce0b534608c02f3cb1b',
    messagingSenderId: '490591202306',
    projectId: 'eventhub-mobileapp',
    storageBucket: 'eventhub-mobileapp.firebasestorage.app',
  );
}
